const icons={scan:'<path d="M8 3H5a2 2 0 0 0-2 2v3m13-5h3a2 2 0 0 1 2 2v3M3 16v3a2 2 0 0 0 2 2h3m8 0h3a2 2 0 0 0 2-2v-3"/><path d="M8 9v1m8-1v1m-8 5q4 4 8 0"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 8.5a2.5 2.5 0 0 1 5 0c0 2-2.5 2-2.5 4M12 16h.01"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',camera:'<path d="M8 5 6 8H3v12h18V8h-3l-2-3Z"/><circle cx="12" cy="13" r="4"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8.5 12 2.5 2.5 4.5-5"/>',check:'<path d="m5 12 4 4L19 6"/>',sound:'<path d="m11 4-6 5H2v6h3l6 5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',mute:'<path d="m11 4-6 5H2v6h3l6 5Z"/><path d="m16 9 5 6m0-6-5 6"/>',refresh:'<path d="M20 11a8 8 0 1 0-2 6M20 4v7h-7"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',back:'<path d="m14 5-7 7 7 7"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.scan}</svg>`;
const expressions=[
{name:'Neutral',title:'Start with a relaxed face.',description:'Take a breath. Look straight at the camera and let your face relax.',tip:'No need to pose. Just be you.',steps:['Keep your head upright and look into the lens.','Relax your eyebrows and keep your lips gently closed.'],feature:'Keep your eyes level with the dotted line.',review:'Your face looks relaxed, with your eyes open and lips gently closed.'},
{name:'Smile',title:'Give us your smile.',description:'Let your cheeks lift and smile as much as feels comfortable.',tip:'A natural smile is all we need.',steps:['Keep looking straight into the camera.','Lift the corners of your mouth. It’s okay to show your teeth.'],feature:'Keep your face in the oval as you smile.',review:'Your smile is clear, with the corners of your mouth lifted.'},
{name:'Frown',title:'Bring your brows together.',description:'Gently move your eyebrows down and toward each other, like you’re concentrating.',tip:'Focus on your eyebrows, not your mouth.',steps:['Keep your eyes open and your head still.','Draw your eyebrows inward and slightly down.'],feature:'Bring your eyebrows down and together.',review:'Your eyebrows are drawn down and together.'},
{name:'Raise eyebrows',title:'Lift your eyebrows.',description:'Raise both eyebrows, as if something pleasantly surprised you.',tip:'Let your forehead do the work.',steps:['Keep your mouth relaxed and your eyes open.','Lift both eyebrows as high as is comfortable.'],feature:'Lift your eyebrows. Keep your head still.',review:'Both eyebrows are lifted and your eyes are open.'},
{name:'Squeeze eyes',title:'Gently squeeze your eyes.',description:'Close both eyes and give them a gentle squeeze. Keep the rest of your face comfortable.',tip:'Turn sound on. You’ll hear when the photo is taken.',steps:['Center your face before closing your eyes.','Close both eyes, squeeze gently, and hold until the capture sound.'],feature:'Close both eyes and hold for the sound.',review:'Both eyes are closed and gently squeezed.'}
];
const state={view:'welcome',index:0,photos:Array(5).fill(null),pending:null,participant:'',demo:false,camera:'idle',cameraError:'',sound:true,countdown:0,returnToReview:false};
let stream=null,timer=null,audioContext=null,cameraRequest=0;
const app=document.querySelector('#app');
const face=(i,cls='small-face')=>`<div class="face-photo ${cls}" style="background-position:${i*25}% 35%" role="img" aria-label="Photographic example: ${expressions[i].name}"></div>`;
function ticks(progress=1){return `<svg class="tick-svg" viewBox="0 0 360 440" fill="none" aria-hidden="true">${Array.from({length:72},(_,i)=>{const a=(i/72)*Math.PI*2-Math.PI/2;return `<line class="${i/72<progress?'active-tick':'muted-tick'}" x1="${180+163*Math.cos(a)}" y1="${220+207*Math.sin(a)}" x2="${180+153*Math.cos(a)}" y2="${220+195*Math.sin(a)}" stroke-linecap="round"/>`;}).join('')}</svg>`;}
function header(){return `<header><div class="brand"><svg class="brand-mark" viewBox="0 0 36 36" fill="none" aria-hidden="true"><path d="M12 3H7a4 4 0 0 0-4 4v5m21-9h5a4 4 0 0 1 4 4v5M3 24v5a4 4 0 0 0 4 4h5m12 0h5a4 4 0 0 0 4-4v-5" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M12 14v2m12-2v2m-12 6q6 6 12 0" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>sense</div><div class="header-right"><span>Facial calibration</span><button class="help-button" data-action="help">${icon('help')}Need a hand?</button></div></header>`;}
function journey(){const active=['welcome','demo'].includes(state.view)?0:['gallery','done'].includes(state.view)?2:1;return `<nav class="journey" aria-label="Calibration progress">${['Get ready','Capture expressions','All done'].map((s,i)=>`${i?'<span class="journey-line" aria-hidden="true"></span>':''}<div class="journey-step ${active===i?'active':active>i?'done':''}" ${active===i?'aria-current="step"':''}><span>${active>i?icon('check'):i+1}</span><span>${s}</span></div>`).join('')}</nav>`;}
function strip(capture=false){return `<section class="${capture?'capture-strip':'expression-strip'}" aria-label="Five required expressions">${!capture?'<div class="strip-heading"><span class="eyebrow">FIVE LITTLE EXPRESSIONS</span><span>We’ll take them one at a time</span></div>':''}<div class="expression-list">${expressions.map((e,i)=>`<div class="expression-item ${capture&&state.index===i?'current':''}" ${capture&&state.index===i?'aria-current="step"':''}>${face(i)}${state.photos[i]&&capture?`<div class="expression-check">${icon('check')}</div>`:''}<div><strong>${e.name}</strong><span>${capture?(state.photos[i]?'Completed':state.index===i?'Current expression':'Up next'):String(i+1).padStart(2,'0')}</span></div></div>`).join('')}</div></section>`;}
function welcome(){return `<div class="workspace fade-in"><div class="hero-grid"><section class="welcome-copy"><h1>Let’s get to know <br>your expressions.</h1><p class="intro">Five simple expressions, one at a time.<br>We’ll guide you through every one.</p><div class="facts"><span>${icon('clock')}About 2 minutes</span><span>${icon('camera')}5 guided photos</span></div><div class="welcome-checks"><div><span class="soft-icon">${icon('sun')}</span>Find soft,<br>even light</div><div><span class="soft-icon">${icon('scan')}</span>Keep your face<br>uncovered</div></div><form id="start-form" novalidate><div class="form-row"><div><label class="field-label" for="participant">Participant code</label><input id="participant" name="participant" autocomplete="off" maxlength="40" placeholder="e.g. P001" aria-describedby="participant-note" required></div><button class="button primary" type="submit">Set up my camera</button></div><p id="participant-note" class="sr-only">Use your participant code. Your real name is not needed.</p><p id="participant-error" class="field-error" role="alert"></p></form><button class="quiet demo-link" data-action="demo">Watch the guided demo</button></section><div class="welcome-visual"><div class="welcome-portrait"><div class="portrait-circle">${face(0,'hero-face')}</div><div class="welcome-ticks">${ticks(.73)}</div></div><div class="visual-foot">${icon('scan')}<div><strong>Find your place in the frame.</strong><span>We’ll help with the rest.</span></div></div></div></div>${strip()}</div>`;}
function render(){app.innerHTML=`${header()}<main>${journey()}${state.demo&&state.view!=='welcome'?`<div class="demo-banner">${icon('info')}Guided demo · Watch the examples. Your camera stays off.</div>`:''}${state.view==='welcome'?welcome():state.view==='demo'?demoView():state.view==='photoReview'?photoReviewView():state.view==='capture'?captureView():state.view==='gallery'?galleryView():doneView()}<p class="page-footer">${icon('lock')}Your photos stay in this tab. Nothing is uploaded.</p><div id="announcer" class="sr-only" aria-live="polite" aria-atomic="true"></div></main>`;if(state.view==='capture')attachVideo();}
function announce(text){const el=document.getElementById('announcer');if(el)el.textContent=text;}
render();
function captureView(){
  const e=expressions[state.index];
  const progress=state.photos.filter(Boolean).length/5;
  return `<div class="workspace fade-in"><div class="capture-layout"><section class="capture-copy">
    <span class="step-count">EXPRESSION ${String(state.index+1).padStart(2,'0')} / 05</span><h2>${e.title}</h2><p class="intro">${e.description}</p>
    <div class="example-box">${face(state.index,'example-portrait')}<div><div class="example-label">Here’s what to do</div><p class="example-hint">Follow this example at your own pace.</p></div></div>
    <div class="instructions">${e.steps.map((s,i)=>`<div class="instruction"><span>${i+1}</span><p>${s}</p></div>`).join('')}</div>
    <details class="mobile-expression-help"><summary>Expression tips</summary><ol>${e.steps.map(step=>`<li>${step}</li>`).join('')}</ol></details>
    <div class="gentle-note">${icon(state.index===4?'sound':'info')}<span>${e.tip}</span></div>
    <button class="back-button" data-action="${state.returnToReview?'back-gallery':'back-home'}">${icon('back')}${state.returnToReview?'Back to all photos':'Back to getting ready'}</button>
  </section><section aria-label="Camera and capture"><div class="capture-stage">
    ${state.demo?face(state.index,'demo-face'):'<video class="camera-video" id="camera-video" autoplay muted playsinline aria-label="Mirrored live camera preview"></video>'}
    <div class="camera-shade"></div><div class="camera-ticks">${ticks(progress)}</div><div class="alignment-guide" aria-hidden="true"></div>
    <div class="camera-status">${icon(state.demo?'info':'camera')}${state.demo?'Example preview':'Camera preview'}</div>
    <div class="camera-controls"><button class="icon-button" data-action="sound" aria-label="${state.sound?'Turn sound off':'Turn sound on'}" aria-pressed="${state.sound}">${icon(state.sound?'sound':'mute')}</button></div>
    <div class="camera-bottom"><span class="camera-pill">${e.feature}</span></div>
    ${!state.demo&&state.camera!=='live'?cameraPlaceholder():''}<div id="countdown-slot"></div>
  </div><div class="capture-actions"><button class="button primary" id="capture-button" data-action="capture" ${!state.demo&&state.camera!=='live'?'disabled':''}>${icon('camera')}Capture ${e.name.toLowerCase()}</button></div>
  <p class="camera-caption">A 3-second countdown gives you time to get ready.</p></section></div>${strip(true)}</div>`;
}
function photoReviewView(){
  const e=expressions[state.index];
  const confirmed=state.photos.filter(Boolean).length;
  const continueLabel=state.returnToReview?'Keep this photo':state.index===4?'Review all 5 photos':'Use photo & continue';
  return `<section class="workspace photo-review fade-in" aria-labelledby="photo-review-title">
    <div class="review-heading">
      <div class="review-title-group"><div class="review-status"><span>${icon('check')}</span>Photo taken</div><h2 id="photo-review-title">Take a quick look.</h2><p>Make sure your face is clear and matches the example.</p></div>
      <div class="review-step-label"><strong>${e.name}</strong><span>Expression ${state.index+1} of 5</span></div>
    </div>
    <div class="review-body">
      <figure class="review-image" aria-label="Your captured ${e.name.toLowerCase()} photo">${state.demo?face(state.index,'review-demo-photo'):`<img src="${state.pending}" alt="Your ${e.name.toLowerCase()} photo">`}</figure>
      <aside class="review-guide" aria-labelledby="review-guide-title">
        <div class="review-checks-group"><h3 id="review-guide-title">Before you continue</h3><p>Check these three things in your photo.</p>
          <ul class="review-checklist"><li>${icon('scan')}<span>Your whole face is in the frame</span></li><li>${icon('sun')}<span>Your face is clear and evenly lit</span></li><li>${icon('camera')}<span>Your expression matches the example</span></li></ul>
        </div>
        <div class="review-reference"><span class="review-reference-label">EXPRESSION REFERENCE</span><div class="review-reference-content">${face(state.index,'review-reference-photo')}<div><h3>${e.name}</h3><p>${e.steps[1]}</p></div></div></div>
      </aside>
    </div>
    <div class="review-action-bar">
      <button class="back-button" data-action="${state.returnToReview?'back-gallery':'back-home'}">${icon('back')}${state.returnToReview?'Back to all photos':'Back to getting ready'}</button>
      <div class="review-action-buttons"><button class="button secondary" data-action="retake">${icon('refresh')}Retake photo</button><button class="button primary" data-action="use-photo">${continueLabel}</button></div>
    </div>
    <div class="review-progress"><div class="review-progress-heading"><span>Your expressions</span><span>${confirmed} of 5 confirmed</span></div>${strip(true)}</div>
  </section>`;
}
function cameraPlaceholder(){if(state.camera==='starting')return `<div class="camera-placeholder"><div class="placeholder-icon">${icon('camera')}</div><h3>Let’s turn on your camera.</h3><p>Choose Allow in your browser’s camera prompt. We only need your camera, not your microphone.</p><button class="button secondary" data-action="demo">Try the demo instead</button></div>`;return `<div class="camera-placeholder"><div class="placeholder-icon">${icon('camera')}</div><h3>${state.camera==='error'?'Your camera needs a little help.':'Ready when you are.'}</h3><p>${state.cameraError||'Turn on your camera to find your place in the frame. Nothing is captured until you choose.'}</p><button class="button primary" data-action="enable-camera">${state.camera==='error'?'Try camera again':'Turn on camera'}</button><button class="quiet" data-action="demo">Explore the demo</button></div>`;}
function galleryView(){return `<section class="workspace gallery-view fade-in"><div class="photo-check">${icon('check')}</div><span class="eyebrow">5 OF 5 EXPRESSIONS CAPTURED</span><h2>That’s every side of you.</h2><p class="intro">Take one last look. You can retake any photo before finishing.</p><div class="gallery-grid">${expressions.map((e,i)=>`<div class="gallery-card"><div class="gallery-image">${state.demo?face(i,'gallery-face'):`<img src="${state.photos[i]}" alt="Your ${e.name.toLowerCase()} photo">`}</div><h3>${icon('check')}${e.name}</h3><button class="quiet" data-action="edit-photo" data-index="${i}" aria-label="Retake ${e.name.toLowerCase()}">Retake photo</button></div>`).join('')}</div><div class="gallery-actions"><button class="button primary wide" data-action="finish" ${state.photos.every(Boolean)?'':'disabled'}>${icon('check')}Finish calibration</button></div><p class="gallery-foot">All five expressions are required. Your photos stay in this browser tab.</p></section>`;}
function doneView(){return `<section class="workspace success-panel fade-in"><div class="success-orbit">${icon('check')}</div><span class="eyebrow">CALIBRATION COMPLETE</span><h2>All five. All done.<br>Thank you for being you.</h2><p>You’ve completed every expression. ${state.demo?'You’ve reached the end of the demo. Ready to try it with your own camera?':'Your five photos are ready to review in this tab. You can now close it to clear them.'}</p><div class="success-thumbs">${expressions.map((_,i)=>state.demo?face(i):`<img class="small-face" style="object-fit:cover" src="${state.photos[i]}" alt="Completed ${expressions[i].name.toLowerCase()}">`).join('')}</div><button class="button primary" data-action="${state.demo?'try-camera':'back-gallery'}">${state.demo?'Try with my camera':'View my photos'}</button><p class="text-small">${state.demo?'The camera will only turn on with your permission.':'Photos are not uploaded. Refreshing or closing this tab clears them.'}</p></section>`;}
function stopCamera(){cameraRequest++;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}state.camera='idle';}
async function enableCamera(){if(state.demo)return;if(stream)stopCamera();if(!navigator.mediaDevices?.getUserMedia){state.camera='error';state.cameraError='Camera access needs a secure browser. Open this page with HTTPS or use the demo.';render();return;}const req=++cameraRequest;state.camera='starting';state.cameraError='';render();try{const nextStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:960}},audio:false});if(req!==cameraRequest||state.demo||state.view!=='capture'){nextStream.getTracks().forEach(t=>t.stop());return;}stream=nextStream;state.camera='live';stream.getVideoTracks()[0].addEventListener('ended',()=>{if(stream===nextStream){stream=null;state.camera='error';state.cameraError='The camera was disconnected. Reconnect it, then try again.';cancelCountdown();render();}});render();announce('Camera ready. Center your face in the oval.');}catch(err){if(req!==cameraRequest)return;state.camera='error';state.cameraError=err.name==='NotAllowedError'?'Camera access is blocked. Allow camera access in your browser’s site settings, then try again.':err.name==='NotFoundError'?'No camera was found. Connect a camera, or explore the demo.':err.name==='NotReadableError'?'Another app may be using your camera. Close it, then try again.':'We couldn’t open your camera. Check its connection and try again.';render();}}
function attachVideo(){const v=document.getElementById('camera-video');if(v&&stream&&state.camera==='live'){const attachedStream=stream;v.srcObject=stream;v.play().catch(()=>{if(!v.isConnected||state.view!=='capture'||stream!==attachedStream)return;stopCamera();cancelCountdown();state.camera='error';state.cameraError='The camera preview could not start. Try opening your camera again.';render();});}}
function sound(frequency=650,duration=.12){if(!state.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);osc.frequency.value=frequency;gain.gain.value=.045;osc.start();gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);osc.stop(audioContext.currentTime+duration);}catch{}}
function cancelCountdown(){clearInterval(timer);timer=null;state.countdown=0;}
function updateCountdown(){const slot=document.querySelector('#countdown-slot');if(slot)slot.innerHTML=state.countdown?`<div class="countdown-layer" role="status"><span class="countdown-number">${state.countdown}</span><p>${state.index===4?'Gently squeeze your eyes':'Hold your expression'}</p></div>`:'';const button=document.querySelector('#capture-button');if(button){button.innerHTML=state.countdown?'Cancel countdown':`${icon('camera')}Capture ${expressions[state.index].name.toLowerCase()}`;button.dataset.action=state.countdown?'cancel':'capture';}announce(state.countdown?`${state.countdown}. Hold your expression.`:'Countdown canceled.');}
function capture(){if(state.view!=='capture'||timer||(!state.demo&&state.camera!=='live'))return;if(!state.demo){const video=document.getElementById('camera-video');if(!video?.videoWidth){announce('The camera is still starting. Please try again in a moment.');return;}}state.countdown=3;sound(500);updateCountdown();timer=setInterval(()=>{state.countdown--;if(state.countdown>0){sound(500);updateCountdown();}else{clearInterval(timer);timer=null;takePhoto();}},1000);}
function takePhoto(){if(state.view!=='capture')return;if(state.demo){state.pending=`demo-${state.index}`;}else{const v=document.getElementById('camera-video');if(!v||!v.videoWidth||!stream){cancelCountdown();state.camera='error';state.cameraError='The camera stopped before the photo was taken. Try again when you’re ready.';render();return;}const c=document.createElement('canvas');const box=v.getBoundingClientRect();const ratio=box.width/box.height;c.width=Math.min(v.videoWidth,960);c.height=Math.round(c.width/ratio);const sourceRatio=v.videoWidth/v.videoHeight;let sw=v.videoWidth,sh=v.videoHeight;if(sourceRatio>ratio)sw=sh*ratio;else sh=sw/ratio;const ctx=c.getContext('2d');ctx.translate(c.width,0);ctx.scale(-1,1);ctx.drawImage(v,(v.videoWidth-sw)/2,(v.videoHeight-sh)/2,sw,sh,0,0,c.width,c.height);state.pending=c.toDataURL('image/jpeg',.9);}sound(950,.3);state.view='photoReview';render();announce('Photo taken. Review your photo, then keep it or retake.');focusHeading();}
function focusHeading(){const el=app.querySelector('main h1,main h2');if(el){el.tabIndex=-1;el.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
function startDemo(){cancelCountdown();stopCamera();state.demo=true;state.camera='idle';state.photos=Array(5).fill(null);state.index=0;state.pending=null;state.returnToReview=false;beginGuidedDemo();}
function usePhoto(){if(state.view!=='photoReview'||!state.pending)return;state.photos[state.index]=state.pending;state.pending=null;if(state.returnToReview||state.photos.every(Boolean)){state.view='gallery';state.returnToReview=false;stopCamera();}else{state.index=state.photos.findIndex(p=>!p);state.view='capture';}render();focusHeading();}
function editPhoto(index){if(!Number.isInteger(index)||index<0||index>=5||!state.photos.every(Boolean))throw new Error('Retakes are available after all five expressions are complete.');state.index=index;state.view='capture';state.returnToReview=true;state.pending=null;render();focusHeading();if(!state.demo)enableCamera();}
function backHome(){pauseDemo();cancelCountdown();stopCamera();state.view='welcome';state.pending=null;render();const input=document.getElementById('participant');if(input)input.value=state.participant;focusHeading();}
function goGallery(){if(!state.photos.every(Boolean))return;cancelCountdown();stopCamera();state.view='gallery';state.pending=null;state.returnToReview=false;render();focusHeading();}
function finish(){if(!state.photos.every(Boolean)||state.view!=='gallery')throw new Error('Complete and confirm all five expressions before finishing.');stopCamera();state.view='done';render();focusHeading();}
app.addEventListener('submit',e=>{if(e.target.id!=='start-form')return;e.preventDefault();const input=document.getElementById('participant');const value=input.value.trim();if(!value){input.setAttribute('aria-invalid','true');document.getElementById('participant-error').textContent='Add your participant code to continue.';input.focus();return;}const startingNew=state.demo||value!==state.participant||state.photos.every(Boolean);if(startingNew){state.photos=Array(5).fill(null);state.pending=null;}pauseDemo();state.participant=value;state.demo=false;state.view='capture';state.returnToReview=false;state.index=state.photos.findIndex(p=>!p);render();focusHeading();enableCamera();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;switch(action){case'help':pauseDemo();if(timer){cancelCountdown();updateCountdown();}document.getElementById('help-dialog').showModal();break;case'close-help':document.getElementById('help-dialog').close();break;case'demo':startDemo();break;case'demo-toggle':demoPlayback.playing?pauseDemo():playDemo();break;case'demo-replay':pauseDemo();seekDemo(0);playDemo();if(e.detail)showDemoPortrait();break;case'demo-chapter':seekDemo(demoSceneStart(Number(b.dataset.index)));playDemo();if(e.detail)showDemoPortrait();break;case'demo-voice':demoPlayback.voice=!demoPlayback.voice;updateDemoVoiceButton();if(demoPlayback.voice){if(demoPlayback.playing)speakDemo();else playDemo();}else stopDemoVoice();break;case'enable-camera':enableCamera();break;case'capture':capture();break;case'cancel':cancelCountdown();updateCountdown();break;case'sound':state.sound=!state.sound;b.setAttribute('aria-pressed',state.sound);b.setAttribute('aria-label',state.sound?'Turn sound off':'Turn sound on');b.innerHTML=icon(state.sound?'sound':'mute');sound(700);break;case'retake':state.pending=null;state.view='capture';render();focusHeading();break;case'use-photo':usePhoto();break;case'edit-photo':editPhoto(Number(b.dataset.index));break;case'finish':finish();break;case'back-home':backHome();break;case'back-gallery':goGallery();break;case'try-camera':state.demo=false;state.photos=Array(5).fill(null);state.index=0;backHome();break;}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseDemo();if(document.hidden&&timer){cancelCountdown();updateCountdown();}});
window.addEventListener('pagehide',()=>{pauseDemo();cancelCountdown();stopCamera();state.photos.fill(null);state.pending=null;state.index=0;state.returnToReview=false;state.demo=false;state.view='welcome';render();});
window.addEventListener('pageshow',e=>{if(e.persisted){pauseDemo();state.view='welcome';state.photos.fill(null);state.pending=null;state.index=0;state.returnToReview=false;state.demo=false;render();}});
// The browser agent can inspect progress without camera access or photo data.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const add=tool=>Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});add({name:'get_calibration_progress',description:'Read the visible calibration step and completion counts. Does not expose participant codes, camera frames, or photos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments expected.');return{view:state.view,mode:state.demo?'demo':'camera',expression:expressions[state.index].name,completed:state.photos.filter(Boolean).length,total:5};}});add({name:'start_calibration_demo',description:'Play a guided walkthrough that automatically shows all five expressions with captions and playback controls. Never requests camera permission. Available only from the welcome screen.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments expected.');if(state.view!=='welcome')throw new Error('Return to the welcome screen before starting a demo.');startDemo();return{view:state.view,mode:'demo',completed:0,total:5};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
